export const RAMOS_DISPONIVEIS = [
  "Academia",
  "Acai",
  "Barbearia",
  "Cafe",
  "Clinica odontologica",
  "Construtora",
  "Consultorio",
  "Distribuidora",
  "Escritorio contabil",
  "Estetica",
  "Farmacia",
  "Fotografo",
  "Hamburgueria",
  "Hotel",
  "Imobiliaria",
  "Industria",
  "Loja de roupas",
  "Manicure",
  "Massagem",
  "Oficina mecanica",
  "Otica",
  "Padaria",
  "Petshop",
  "Pilates",
  "Pizzaria",
  "Pousada",
  "Restaurante",
  "Salao de beleza",
  "Spa",
  "Transportadora",
] as const;

export type Ramo = (typeof RAMOS_DISPONIVEIS)[number];
