export const RAMOS_DISPONIVEIS = [
  "Academia",
  "Acai",
  "Barbearia",
  "Cafe",
  "Clinica odontologica",
  "Consultorio",
  "Estetica",
  "Escritorio contabil",
  "Farmacia",
  "Fotografo",
  "Hamburgueria",
  "Hotel",
  "Loja de roupas",
  "Manicure",
  "Massagem",
  "Oficina mecanica",
  "Otica",
  "Padaria",
  "Petshop",
  "Pilates",
  "Pizzaria",
  "Pousada",
  "Restaurante",
  "Salao de beleza",
  "Spa",
] as const;

export type Ramo = (typeof RAMOS_DISPONIVEIS)[number];
